import { createFileRoute } from "@tanstack/react-router";
import { Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/pilates/configuracoes")({component:Configuracoes});
function Configuracoes(){const [tab,setTab]=useState<"Professores"|"Planos">("Professores"),[teachers,setTeachers]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[name,setName]=useState(""),[duration,setDuration]=useState("1"),[error,setError]=useState("");
const load=async()=>{const db=supabase as any;const [t,p]=await Promise.all([db.from("teachers").select("*").order("name"),db.from("plans").select("*").order("duration_months")]);if(t.error||p.error)setError(t.error?.message||p.error?.message);setTeachers(t.data||[]);setPlans(p.data||[])};useEffect(()=>{load()},[]);
const addTeacher=async()=>{const teacherName=name.trim();if(!teacherName){setError("Informe o nome do professor.");return;}setError("");const {data,error}=await (supabase as any).from("teachers").insert({name:teacherName,active:true}).select().single();if(error){setError("Não foi possível adicionar o professor: "+error.message);return;}if(!data){setError("O professor não foi retornado após o cadastro.");return;}setName("");await load()};
const addPlan=async()=>{if(!name.trim())return;const {error}=await (supabase as any).from("plans").insert({name:name.trim(),duration_months:Number(duration)});if(error)setError(error.message);else{setName("");load()}};
const del=async(table:string,id:string)=>{const {error}=await (supabase as any).from(table).delete().eq("id",id);if(error)setError(error.message);else load()};
return <div className="mx-auto max-w-5xl"><p className="text-sm font-medium text-black/45">Pilates</p><h1 className="mt-1 text-3xl font-semibold">Configurações</h1><p className="mt-2 text-sm text-black/55">Gerencie professores e planos disponíveis no cadastro de alunos.</p>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 flex gap-2 border-b"><button onClick={()=>setTab("Professores")} className={`px-4 py-3 text-sm ${tab==="Professores"?"border-b-2 border-black font-medium":"text-black/50"}`}>Professores</button><button onClick={()=>setTab("Planos")} className={`px-4 py-3 text-sm ${tab==="Planos"?"border-b-2 border-black font-medium":"text-black/50"}`}>Planos</button></div><div className="mt-6 flex gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder={tab==="Professores"?"Nome do professor":"Nome do plano"} className="flex-1 rounded-xl border border-black/10 p-3 text-sm"/>{tab==="Planos"&&<select value={duration} onChange={e=>setDuration(e.target.value)} className="rounded-xl border border-black/10 px-3"><option value="1">1 mês</option><option value="3">3 meses</option><option value="6">6 meses</option></select>}<button onClick={tab==="Professores"?addTeacher:addPlan} className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-3 text-sm text-white"><Plus size={17}/>Adicionar</button></div><div className="mt-6 space-y-2">{(tab==="Professores"?teachers:plans).map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-xl border border-black/10 bg-white p-4"><div><strong>{x.name}</strong>{tab==="Planos"&&<span className="ml-3 text-sm text-black/45">{x.duration_months} mês(es)</span>}</div><button onClick={()=>del(tab==="Professores"?"teachers":"plans",x.id)} className="text-red-600"><Trash2 size={17}/></button></div>)}</div></div>}