import { createFileRoute, Link, Outlet, useRouterState } from "@tanstack/react-router";
import { Filter, Plus, Search, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

type Student={id:string;full_name:string;phone:string|null;active:boolean;plan:string;teacher:string;due:string|null;planStatus:string;contract:string;assessment:string;financial:string};
const fmt=(d:string|null)=>d?new Intl.DateTimeFormat("pt-BR").format(new Date(d+"T00:00:00")):"—";
const formatPhone=(value:string)=>{const d=value.replace(/\\D/g,"").slice(0,11);return d.length<=2?d: d.length<=3?`(${d.slice(0,2)}) ${d.slice(2)}`:d.length<=7?`(${d.slice(0,2)}) ${d.slice(2,3)} ${d.slice(3)}`:`(${d.slice(0,2)}) ${d.slice(2,3)} ${d.slice(3,7)}-${d.slice(7)}`};
const formatMoneyInput=(value:string)=>{const d=value.replace(/\\D/g,"");return d?`${(Number(d)/100).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}`:"";};
const moneyToNumber=(value:string)=>Number(value.replace(/\\./g,"").replace(",","."))||0;
const statusClass=(v:string)=>["Vencida","Vencendo","Pendente","Vencido"].includes(v)?"bg-red-50 text-red-700":v.includes("Próxima")?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700";

export const Route=createFileRoute("/pilates/alunos")({component:Alunos});
function Alunos(){
 const pathname=useRouterState({select:s=>s.location.pathname}); const [rows,setRows]=useState<Student[]>([]); const [plans,setPlans]=useState<any[]>([]); const [teachers,setTeachers]=useState<any[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(""); const [search,setSearch]=useState(""),[activity,setActivity]=useState("Todos"),[teacher,setTeacher]=useState("Todos"),[plan,setPlan]=useState("Todos"),[showForm,setShowForm]=useState(false),[deleting,setDeleting]=useState<Student|null>(null);
 const [form,setForm]=useState({full_name:"",phone:"",plan_id:"",teacher_id:"",monthly_value:"",start_date:new Date().toISOString().slice(0,10),due_date:""});
 async function load(){
  setLoading(true);setError("");
  const db=supabase as any;
  const [s,p,t]=await Promise.all([db.from("students").select("*,student_plans(plan_id,teacher_id,due_date,status,plans(name),teachers(name)),student_contracts(status,end_date),physical_assessments(status,next_assessment_date),student_payments(status,due_date)").order("full_name"),db.from("plans").select("*").order("duration_months"),db.from("teachers").select("*").eq("active",true).order("name")]);
  if(s.error){setError(s.error.message);setLoading(false);return;} if(p.error||t.error){setError(p.error?.message||t.error?.message||"Erro ao carregar dados");}
  setPlans(p.data||[]);setTeachers(t.data||[]);
  setRows((s.data||[]).map((x:any)=>{const sp=(x.student_plans||[])[0]||{};const c=(x.student_contracts||[])[0]||{};const a=(x.physical_assessments||[])[0]||{};const pay=(x.student_payments||[])[0]||{};return {id:x.id,full_name:x.full_name,phone:x.phone,active:x.active,plan:sp.plans?.name||"—",teacher:sp.teachers?.name||"—",due:sp.due_date||null,planStatus:sp.status||"—",contract:c.status||"—",assessment:a.status||"—",financial:pay.status==="Pago"?"Regular":pay.status||"—"};}));setLoading(false);
 }
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>rows.filter(x=>(!search||x.full_name.toLowerCase().includes(search.toLowerCase())||(x.phone||"").includes(search))&&(activity==="Todos"||(activity==="Ativos"?x.active:!x.active))&&(teacher==="Todos"||x.teacher===teacher)&&(plan==="Todos"||x.plan===plan)),[rows,search,activity,teacher,plan]);
 async function save(){if(!form.full_name||!form.plan_id||!form.start_date||!form.due_date){setError("Preencha nome, plano, início e vencimento.");return;}const db=supabase as any;const {data:st,error:e}=await db.from("students").insert({full_name:form.full_name,phone:form.phone||null}).select().single();if(e){setError(e.message);return;}const {error:pe}=await db.from("student_plans").insert({student_id:st.id,plan_id:form.plan_id,teacher_id:form.teacher_id||null,monthly_value:moneyToNumber(form.monthly_value),start_date:form.start_date,due_date:form.due_date});if(pe){setError(pe.message);return;}await db.from("student_audit_log").insert({student_id:st.id,action:"Cadastro criado",details:{source:"interface"}});setShowForm(false);setForm({full_name:"",phone:"",plan_id:"",teacher_id:"",monthly_value:"",start_date:new Date().toISOString().slice(0,10),due_date:""});load();}
 async function remove(){if(!deleting)return;const {error}=await (supabase as any).from("students").delete().eq("id",deleting.id);if(error){setError(error.message);return;}setDeleting(null);load();}
 if(pathname!=="/pilates/alunos")return <Outlet/>;
 return <div className="w-full max-w-none"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-black/45">Pilates</p><h1 className="mt-1 text-3xl font-semibold">Cadastro de Alunos</h1><p className="mt-2 text-sm text-black/55">Dados sincronizados com o Supabase.</p></div><button onClick={()=>setShowForm(true)} className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-3 text-sm font-medium text-white"><Plus size={18}/>Novo aluno</button></div>
 {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="border-y border-black/10 py-4"><div className="flex gap-3"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-black/40" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar aluno por nome ou telefone..." className="w-full rounded-xl border border-black/10 bg-white py-3 pl-10 pr-4 text-sm"/></label><Filter className="mt-3 text-black/40" size={18}/></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><select value={activity} onChange={e=>setActivity(e.target.value)} className="rounded-xl border border-black/10 p-2.5 text-sm"><option>Todos</option><option>Ativos</option><option>Inativos</option></select><select value={teacher} onChange={e=>setTeacher(e.target.value)} className="rounded-xl border border-black/10 p-2.5 text-sm"><option>Todos</option>{teachers.map(t=><option key={t.id}>{t.name}</option>)}</select><select value={plan} onChange={e=>setPlan(e.target.value)} className="rounded-xl border border-black/10 p-2.5 text-sm"><option>Todos</option>{plans.map(p=><option key={p.id}>{p.name}</option>)}</select><div className="px-2 py-2.5 text-sm text-black/45">{filtered.length} aluno(s)</div></div></div>
 <div className="w-full overflow-x-auto"><table className="w-full min-w-[1450px] text-left text-sm"><thead className="bg-black/[.025] text-xs uppercase text-black/45"><tr>{["Foto","Nome","Telefone","Plano atual","Professor","Vencimento","Status plano","Contrato","Avaliação física","Financeiro","Ações"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-black/5">{filtered.map(x=><tr key={x.id}><td className="px-4 py-4"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-black/10 text-xs font-semibold">{x.full_name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div></td><td className="px-4 py-4 font-medium"><Link to="/pilates/alunos/$alunoId" params={{alunoId:x.id}}>{x.full_name}</Link></td><td className="px-4 py-4">{x.phone||"—"}</td><td className="px-4 py-4">{x.plan}</td><td className="px-4 py-4">{x.teacher}</td><td className="px-4 py-4">{fmt(x.due)}</td><td className="px-4 py-4"><span className="rounded-full px-2 py-1 text-xs bg-emerald-50 text-emerald-700">{x.active?"Ativo":"Inativo"}</span></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs ${statusClass(x.contract)}`}>{x.contract}</span></td><td className="px-4 py-4">{x.assessment}</td><td className="px-4 py-4">{x.financial}</td><td className="px-4 py-4"><button onClick={()=>setDeleting(x)} className="inline-flex items-center gap-1 text-red-600"><Trash2 size={16}/>Excluir</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={11} className="px-4 py-12 text-center text-black/45">Nenhum aluno cadastrado.</td></tr>}</tbody></table>{loading&&<div className="py-8 text-center text-sm text-black/45">Carregando alunos...</div>}</div>
 {showForm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Novo aluno</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} placeholder="Nome completo" className="rounded-xl border border-black/10 p-3 text-sm"/><input value={form.phone} onChange={e=>setForm({...form,phone:formatPhone(e.target.value)})} placeholder="(00) 0 0000-0000" inputMode="numeric" maxLength={16} className="rounded-xl border border-black/10 p-3 text-sm"/><input value={form.monthly_value} onChange={e=>setForm({...form,monthly_value:formatMoneyInput(e.target.value)})} placeholder="0,00" inputMode="numeric" className="rounded-xl border border-black/10 p-3 text-sm"/><select value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value})} className="rounded-xl border border-black/10 p-3 text-sm"><option value="">Selecione o plano</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={form.teacher_id} onChange={e=>setForm({...form,teacher_id:e.target.value})} className="rounded-xl border border-black/10 p-3 text-sm"><option value="">Sem professor</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})} className="rounded-xl border border-black/10 p-3 text-sm"/><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} className="rounded-xl border border-black/10 p-3 text-sm"/></div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setShowForm(false)} className="rounded-xl border px-4 py-2">Cancelar</button><button onClick={save} className="rounded-xl bg-black px-4 py-2 text-white">Salvar aluno</button></div></div></div>}
 {deleting&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Excluir aluno?</h2><p className="mt-2 text-sm text-black/60">A exclusão é permanente e remove os dados vinculados.</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setDeleting(null)} className="rounded-xl border px-4 py-2">Cancelar</button><button onClick={remove} className="rounded-xl bg-red-600 px-4 py-2 text-white">Excluir</button></div></div></div>}
 </div>
}