import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Download, ExternalLink, RotateCcw } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
const tabs=["Informações pessoais","Plano","Contrato","Avaliação física","Financeiro","Histórico"] as const; type Tab=typeof tabs[number];
const fmt=(d:any)=>d?new Intl.DateTimeFormat("pt-BR").format(new Date(d+"T00:00:00")):"—"; const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const badge=(x:string)=> <span className="inline-flex rounded-full bg-black/5 px-2.5 py-1 text-xs font-medium">{x}</span>;
export const Route=createFileRoute("/pilates/alunos/$alunoId")({component:PerfilAluno});
function PerfilAluno(){const [tab,setTab]=useState<Tab>("Informações pessoais"),[data,setData]=useState<any>(null),[error,setError]=useState("");const {alunoId}=Route.useParams();
useEffect(()=>{(async()=>{const db=supabase as any;const {data,error}=await db.from("students").select("*,student_plans(*,plans(name),teachers(name)),student_contracts(*),physical_assessments(*),student_payments(*),student_audit_log(*)").eq("id",alunoId).single();if(error)setError(error.message);else setData(data);})();},[alunoId]);
if(error)return <div className="p-6 text-red-600">{error}</div>;if(!data)return <div className="p-6 text-sm text-black/45">Carregando perfil...</div>;
const plan=(data.student_plans||[])[0],contract=(data.student_contracts||[])[0],assessment=(data.physical_assessments||[])[0], initials=data.full_name.split(" ").map((x:string)=>x[0]).slice(0,2).join("");
return <div className="mx-auto max-w-7xl"><Link to="/pilates/alunos" className="mb-5 inline-flex items-center gap-2 text-sm text-black/55"><ArrowLeft size={17}/>Voltar para alunos</Link><div className="rounded-2xl border border-black/10 bg-white p-5 sm:p-6"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-black/10 text-lg font-semibold">{initials}</div><div><p className="text-sm text-black/45">Perfil do aluno</p><h1 className="text-2xl font-semibold">{data.full_name}</h1>{badge(data.active?"Ativo":"Inativo")}</div></div><div className="mt-6 flex gap-2 overflow-x-auto border-t pt-4">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-sm ${tab===t?"bg-black text-white":"text-black/55"}`}>{t}</button>)}</div></div><div className="mt-5 rounded-2xl border border-black/10 bg-white p-6">{tab==="Informações pessoais"&&<Info d={data}/>} {tab==="Plano"&&<Plan d={plan}/>} {tab==="Contrato"&&<Contract d={contract}/>} {tab==="Avaliação física"&&<Assessments rows={data.physical_assessments||[]}/>} {tab==="Financeiro"&&<Financial rows={data.student_payments||[]}/>} {tab==="Histórico"&&<History rows={data.student_audit_log||[]}/>}</div></div>}
function Field({l,v}:{l:string;v:any}){return <div><dt className="text-xs uppercase text-black/40">{l}</dt><dd className="mt-1 text-sm font-medium">{v||"—"}</dd></div>}
function Info({d}:any){const age=d.birth_date?Math.floor((Date.now()-new Date(d.birth_date).getTime())/31557600000):"—";return <><h2 className="mb-6 text-xl font-semibold">Informações pessoais</h2><dl className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><Field l="Nome" v={d.full_name}/><Field l="Data de nascimento" v={fmt(d.birth_date)}/><Field l="Idade" v={typeof age==="number"?age+" anos":age}/><Field l="Telefone" v={d.phone}/><div><dt className="text-xs uppercase text-black/40">WhatsApp</dt><dd className="mt-1 text-sm font-medium">{d.whatsapp?<a className="underline" href={"https://wa.me/"+d.whatsapp.replace(/\D/g,"")} target="_blank">Abrir conversa</a>:"—"}</dd></div><Field l="E-mail" v={d.email}/><Field l="CPF" v={d.cpf}/><Field l="Endereço" v={d.address}/><Field l="Observações" v={d.notes}/></dl></>}
function Plan({d}:any){return <><h2 className="mb-6 text-xl font-semibold">Plano atual</h2>{d?<dl className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><Field l="Plano" v={d.plans?.name}/><Field l="Professor" v={d.teachers?.name}/><Field l="Valor mensal" v={money(d.monthly_value)}/><Field l="Data de início" v={fmt(d.start_date)}/><Field l="Vencimento" v={fmt(d.due_date)}/><Field l="Status" v={d.status}/></dl>:<p className="text-black/50">Nenhum plano cadastrado.</p>}</>}
function Contract({d}:any){return <><h2 className="mb-6 text-xl font-semibold">Contrato</h2>{d?<><dl className="grid gap-6 sm:grid-cols-3"><Field l="Status" v={d.status}/><Field l="Vigência" v={fmt(d.start_date)+" a "+fmt(d.end_date)}/><Field l="Anexo" v={d.attachment_url?"Contrato disponível":"Sem anexo"}/></dl><div className="mt-6 flex gap-3">{d.attachment_url&&<><a href={d.attachment_url} target="_blank" className="inline-flex items-center gap-2 rounded-xl border px-4 py-2"><ExternalLink size={16}/>Visualizar</a><a href={d.attachment_url} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2"><Download size={16}/>Baixar</a></>}<button className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-2 text-white"><RotateCcw size={16}/>Renovar contrato</button></div></>:<p className="text-black/50">Nenhum contrato cadastrado.</p>}</>}
function Assessments({rows}:any){return <><h2 className="mb-6 text-xl font-semibold">Avaliação física</h2><div className="space-y-3">{rows.length?rows.map((x:any)=><div key={x.id} className="rounded-xl border p-4 text-sm"><strong>{fmt(x.assessment_date)}</strong><p className="mt-1">Próxima: {fmt(x.next_assessment_date)} · {x.status}</p><p className="text-black/55">{x.notes}</p></div>):<p className="text-black/50">Nenhuma avaliação cadastrada.</p>}</div></>}
function Financial({rows}:any){return <><h2 className="mb-6 text-xl font-semibold">Financeiro</h2><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr>{["Vencimento","Valor","Status","Pagamento","Forma","Destino"].map(x=><th key={x} className="border-b p-3 text-xs uppercase text-black/40">{x}</th>)}</tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td className="p-3">{fmt(x.due_date)}</td><td className="p-3">{money(x.amount)}</td><td className="p-3">{x.status}</td><td className="p-3">{fmt(x.paid_at)}</td><td className="p-3">{x.payment_method||"—"}</td><td className="p-3">{x.destination}</td></tr>)}</tbody></table></div></>}
function History({rows}:any){return <><h2 className="mb-6 text-xl font-semibold">Histórico</h2><div className="space-y-4">{rows.length?rows.map((x:any)=><div key={x.id} className="border-l pl-4"><p className="font-medium">{x.action}</p><p className="text-sm text-black/50">{new Date(x.created_at).toLocaleString("pt-BR")}</p></div>):<p className="text-black/50">Nenhuma alteração registrada.</p>}</div></>}