import { createFileRoute } from "@tanstack/react-router";
import { Plus, UserRoundCog, X } from "lucide-react"; import { useEffect,useState } from "react";
import { AuthGuard } from "@/components/AuthGuard"; import { TopBar } from "@/components/TopBar";
import { OficinaSidebar } from "@/components/OficinaSidebar"; import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/projeto-oficina/professores")({component:Professores});
function Professores(){const [rows,setRows]=useState<any[]>([]),[show,setShow]=useState(false),[form,setForm]=useState({name:"",phone:"",email:"",notes:""});
async function load(){const {data}=await supabase.from("oficina_professores").select("*").order("name");setRows(data??[])} useEffect(()=>{void load()},[]);
async function save(e:React.FormEvent){e.preventDefault();await supabase.from("oficina_professores").insert(form);setShow(false);setForm({name:"",phone:"",email:"",notes:""});await load()}
return <AuthGuard><div className="min-h-screen bg-white"><TopBar/><div className="flex min-h-[calc(100vh-64px)]"><OficinaSidebar/><div className="min-w-0 flex-1"><main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl"><header className="mb-6 flex justify-between items-center"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-black/40">Projeto Oficina</p><h1 className="mt-1 text-[30px] font-bold text-[#111827]">Professores</h1></div><button onClick={()=>setShow(true)} className="inline-flex gap-2 rounded-xl bg-[#111827] px-4 py-2.5 text-sm font-medium text-white"><Plus size={16}/> Novo professor</button></header><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(x=><article key={x.id} className="rounded-2xl border border-black/10 p-5"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/5"><UserRoundCog size={18}/></div><h2 className="mt-4 font-semibold">{x.name}</h2><p className="mt-1 text-sm text-black/50">{x.phone||"Sem telefone"}</p><p className="text-sm text-black/50">{x.email||"Sem e-mail"}</p><p className="mt-3 text-xs text-emerald-700">{x.active?"Ativo":"Inativo"}</p></article>)}{!rows.length&&<p className="text-sm text-black/45">Nenhum professor cadastrado.</p>}</section></div></main></div>{show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="font-semibold">Novo professor</h2><button type="button" onClick={()=>setShow(false)}><X size={18}/></button></div><div className="grid gap-4">{F("Nome",<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>)}{F("Telefone",<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/>)}{F("E-mail",<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>)}{F("Observações",<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>)}<button className="rounded-xl bg-[#111827] py-3 text-sm text-white">Salvar professor</button></div></form></div>}</AuthGuard>}
function F(l:string,c:React.ReactNode){return <label><span className="mb-1.5 block text-xs text-black/55">{l}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-black/10 [&_input]:px-3 [&_input]:py-2.5">{c}</div></label>}