import { createFileRoute } from "@tanstack/react-router";
import { CircleDollarSign, Plus, WalletCards } from "lucide-react"; import { useEffect,useState } from "react";
import { AuthGuard } from "@/components/AuthGuard"; import { TopBar } from "@/components/TopBar"; import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/projeto-oficina/financeiro")({component:Financeiro});
function Financeiro(){const [payments,setPayments]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[month,setMonth]=useState(()=>new Date());const start=new Date(month.getFullYear(),month.getMonth(),1).toISOString().slice(0,10),end=new Date(month.getFullYear(),month.getMonth()+1,0).toISOString().slice(0,10);
async function load(){const [{data:p},{data:e}]=await Promise.all([supabase.from("oficina_pagamentos").select("*,oficina_aluno_planos(oficina_alunos(full_name))").gte("due_date",start).lte("due_date",end).order("due_date"),supabase.from("oficina_despesas").select("*").gte("expense_date",start).lte("expense_date",end).order("expense_date")]);setPayments(p??[]);setExpenses(e??[])}useEffect(()=>{void load()},[start,end]);
const recebido=payments.filter(x=>x.status==="Pago").reduce((s,x)=>s+Number(x.amount),0),aberto=payments.filter(x=>x.status==="Em aberto").reduce((s,x)=>s+Number(x.amount),0),despesas=expenses.reduce((s,x)=>s+Number(x.amount),0);
async function pay(id:string){await supabase.from("oficina_pagamentos").update({status:"Pago",paid_at:new Date().toISOString().slice(0,10)}).eq("id",id);await load()}
return <AuthGuard><div className="min-h-screen bg-white"><TopBar/><main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6"><p className="text-xs font-semibold uppercase tracking-[.12em] text-black/40">Projeto Oficina</p><div className="flex items-center justify-between"><h1 className="mt-1 text-[30px] font-bold text-[#111827]">Financeiro</h1><div className="flex gap-2"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} className="rounded-lg border px-3 py-2">‹</button><span className="px-3 py-2 text-sm capitalize">{month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</span><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} className="rounded-lg border px-3 py-2">›</button></div></div></header><div className="mb-6 grid gap-4 sm:grid-cols-3"><Card label="Recebido" value={money(recebido)} icon={<WalletCards size={18}/>}/><Card label="Em aberto" value={money(aberto)} icon={<CircleDollarSign size={18}/>}/><Card label="Despesas" value={money(despesas)} icon={<Plus size={18}/>}/></div><section className="rounded-2xl border border-black/10 overflow-hidden"><div className="border-b p-4 font-semibold">Cobranças do mês</div><table className="w-full text-sm"><thead className="bg-[#fafafa] text-xs text-black/45"><tr><th className="p-4 text-left">Vencimento</th><th className="p-4 text-left">Aluno</th><th className="p-4 text-left">Valor</th><th className="p-4 text-left">Status</th><th className="p-4"></th></tr></thead><tbody>{payments.map(x=><tr key={x.id} className="border-t"><td className="p-4">{new Date(x.due_date+"T12:00:00").toLocaleDateString("pt-BR")}</td><td className="p-4">{x.oficina_aluno_planos?.oficina_alunos?.full_name||"—"}</td><td className="p-4">{money(Number(x.amount))}</td><td className="p-4">{x.status}</td><td className="p-4 text-right">{x.status==="Em aberto"&&<button onClick={()=>pay(x.id)} className="rounded-lg bg-[#111827] px-3 py-2 text-xs text-white">Marcar pago</button>}</td></tr>)}</tbody></table></section><section className="mt-6 rounded-2xl border border-black/10 p-5"><h2 className="font-semibold">Despesas</h2>{expenses.map(x=><div key={x.id} className="flex justify-between border-b py-3 text-sm"><span>{x.description}</span><strong>{money(Number(x.amount))}</strong></div>)}{!expenses.length&&<p className="mt-3 text-sm text-black/45">Nenhuma despesa neste mês.</p>}</section></div></main></div></AuthGuard>}
function Card(p:{label:string;value:string;icon:React.ReactNode}){return <div className="rounded-2xl border border-black/10 p-5"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/5">{p.icon}</div><p className="mt-4 text-xs text-black/45">{p.label}</p><p className="mt-1 text-2xl font-bold">{p.value}</p></div>}function money(v:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v)}