import { createFileRoute } from "@tanstack/react-router";
import { Plus, Search, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { AuthGuard } from "@/components/AuthGuard";
import { TopBar } from "@/components/TopBar";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/projeto-oficina/alunos")({component:Alunos});
function Alunos(){
 const [rows,setRows]=useState<any[]>([]),[search,setSearch]=useState(""),[show,setShow]=useState(false),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({full_name:"",phone:"",whatsapp:"",email:"",birth_date:"",notes:""});
 async function load(){const {data}=await supabase.from("oficina_alunos").select("*").order("full_name");setRows(data??[])}
 useEffect(()=>{void load()},[]);
 const filtered=rows.filter(x=>x.full_name.toLowerCase().includes(search.toLowerCase())||String(x.phone??"").includes(search));
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);await supabase.from("oficina_alunos").insert({...form,birth_date:form.birth_date||null});setForm({full_name:"",phone:"",whatsapp:"",email:"",birth_date:"",notes:""});setShow(false);setSaving(false);await load()}
 return <AuthGuard><div className="min-h-screen bg-white"><TopBar/><main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl"><Head title="Alunos" action={<button onClick={()=>setShow(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#111827] px-4 py-2.5 text-sm font-medium text-white"><Plus size={16}/> Novo aluno</button>}/><div className="mb-5 flex items-center gap-3 rounded-xl border border-black/10 px-4 py-3"><Search size={17} className="text-black/35"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar aluno..." className="w-full outline-none text-sm"/></div><section className="overflow-hidden rounded-2xl border border-black/10"><table className="w-full text-left text-sm"><thead className="bg-[#fafafa] text-xs text-black/45"><tr><th className="px-5 py-3">Aluno</th><th className="px-5 py-3">Telefone</th><th className="px-5 py-3">WhatsApp</th><th className="px-5 py-3">Situação</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="border-t border-black/10"><td className="px-5 py-4 font-medium"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-black/5"><UserRound size={15}/></span>{x.full_name}</div></td><td className="px-5 py-4 text-black/55">{x.phone||"—"}</td><td className="px-5 py-4 text-black/55">{x.whatsapp||"—"}</td><td className="px-5 py-4"><span className={x.active?"text-emerald-700":"text-black/40"}>{x.active?"Ativo":"Inativo"}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={4} className="p-10 text-center text-sm text-black/45">Nenhum aluno encontrado.</td></tr>}</tbody></table></section></div></main></div>{show&&<Modal title="Novo aluno" close={()=>setShow(false)}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{Field("Nome completo",<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/>)}{Field("Telefone",<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/>)}{Field("WhatsApp",<input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/>)}{Field("E-mail",<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>)}{Field("Nascimento",<input type="date" value={form.birth_date} onChange={e=>setForm({...form,birth_date:e.target.value})}/>)}{Field("Observações",<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>)}<button disabled={saving} className="sm:col-span-2 rounded-xl bg-[#111827] px-4 py-3 text-sm font-medium text-white disabled:opacity-40">Salvar aluno</button></form></Modal>}</AuthGuard>
}
function Head(p:{title:string;action:React.ReactNode}){return <header className="mb-6 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-black/40">Projeto Oficina</p><h1 className="mt-1 text-[30px] font-bold leading-[1.2] text-[#111827]">{p.title}</h1></div>{p.action}</header>}
function Field(l:string,c:React.ReactNode){return <label className="block"><span className="mb-1.5 block text-xs font-medium text-black/60">{l}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-black/10 [&_input]:px-3 [&_input]:py-2.5 [&_input]:text-sm">{c}</div></label>}
function Modal(p:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><h2 className="text-lg font-semibold">{p.title}</h2><button onClick={p.close}><X size={18}/></button></div>{p.children}</div></div>}