import { createFileRoute } from "@tanstack/react-router";
import { Plus, X } from "lucide-react"; import { useEffect,useState } from "react";
import { AuthGuard } from "@/components/AuthGuard"; import { TopBar } from "@/components/TopBar";
import { OficinaSidebar } from "@/components/OficinaSidebar"; import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/projeto-oficina/planos")({component:Planos});
function Planos(){const [rows,setRows]=useState<any[]>([]),[show,setShow]=useState(false),[form,setForm]=useState({name:"",duration_months:"1",total_value:"0",monthly_value:"0",payment_method:"Pix",description:""});
async function load(){const {data}=await supabase.from("oficina_planos").select("*").order("duration_months").order("name");setRows(data??[])}useEffect(()=>{void load()},[]);
async function save(e:React.FormEvent){e.preventDefault();await supabase.from("oficina_planos").insert({...form,duration_months:Number(form.duration_months),total_value:Number(form.total_value),monthly_value:Number(form.monthly_value)});setShow(false);await load()}
return <AuthGuard><div className="min-h-screen bg-white"><TopBar/><div className="flex min-h-[calc(100vh-64px)]"><OficinaSidebar/><div className="min-w-0 flex-1"><main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl"><header className="mb-6 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-black/40">Projeto Oficina</p><h1 className="mt-1 text-[30px] font-bold text-[#111827]">Planos</h1><p className="mt-2 text-sm text-black/50">Configure os planos mensal e trimestral e os valores praticados pela Oficina.</p></div><button onClick={()=>setShow(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#111827] px-4 py-2.5 text-sm text-white"><Plus size={16}/> Novo plano</button></header><section className="grid gap-4 sm:grid-cols-2">{rows.map(x=><article key={x.id} className="rounded-2xl border border-black/10 p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{x.name}</h2><p className="mt-1 text-xs text-black/45">{x.duration_months===1?"Cobrança mensal":"Cobrança trimestral"}</p></div><span className="text-xs text-emerald-700">{x.active?"Ativo":"Inativo"}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><Box l="Valor total" v={money(Number(x.total_value))}/><Box l="Valor mensal" v={money(Number(x.monthly_value))}/></div><p className="mt-4 text-xs text-black/45">Forma padrão: {x.payment_method||"—"}</p></article>)}</section></div></main></div>{show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="font-semibold">Novo plano</h2><button type="button" onClick={()=>setShow(false)}><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2">{F("Nome",<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>)}{F("Tipo",<select value={form.duration_months} onChange={e=>setForm({...form,duration_months:e.target.value})}><option value="1">Mensal</option><option value="3">Trimestral</option></select>)}{F("Valor total",<input type="number" step=".01" value={form.total_value} onChange={e=>setForm({...form,total_value:e.target.value})}/>)}{F("Valor mensal",<input type="number" step=".01" value={form.monthly_value} onChange={e=>setForm({...form,monthly_value:e.target.value})}/>)}{F("Forma de pagamento",<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option>Pix</option><option>Cartão</option><option>Dinheiro</option><option>Transferência</option></select>)}{F("Descrição",<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>)}</div><button className="mt-6 w-full rounded-xl bg-[#111827] py-3 text-sm text-white">Salvar plano</button></form></div>}</div></div></AuthGuard>}
function Box(p:{l:string;v:string}){return <div className="rounded-xl border border-black/10 bg-[#fafafa] p-3"><p className="text-xs text-black/45">{p.l}</p><p className="mt-1 font-semibold">{p.v}</p></div>}function F(l:string,c:React.ReactNode){return <label><span className="mb-1.5 block text-xs text-black/55">{l}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-black/10 [&_input]:px-3 [&_input]:py-2.5 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-black/10 [&_select]:px-3 [&_select]:py-2.5">{c}</div></label>}function money(v:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v)}