/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OsteopatiaRouteImport } from './routes/osteopatia'
import { Route as PilatesRouteImport } from './routes/pilates'
import { Route as PilatesAlunosRouteImport } from './routes/pilates.alunos'
import { Route as PilatesConfiguracoesRouteImport } from './routes/pilates.configuracoes'
import { Route as PilatesAulasExperimentaisRouteImport } from './routes/pilates.aulas-experimentais'
import { Route as PilatesAlunoIdRouteImport } from './routes/pilates.alunos.$alunoId'
import { Route as VisualizacaoRouteImport } from './routes/visualizacao'
import { Route as VisualizacaoPilatesRouteImport } from './routes/visualizacao.pilates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OsteopatiaRoute = OsteopatiaRouteImport.update({
  id: '/osteopatia',
  path: '/osteopatia',
  getParentRoute: () => rootRouteImport,
} as any)
const PilatesRoute = PilatesRouteImport.update({
  id: '/pilates',
  path: '/pilates',
  getParentRoute: () => rootRouteImport,
} as any)
const PilatesAulasExperimentaisRoute = PilatesAulasExperimentaisRouteImport.update({ id: '/aulas-experimentais', path: '/aulas-experimentais', getParentRoute: () => PilatesRoute } as any)
const PilatesConfiguracoesRoute = PilatesConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PilatesRoute,
} as any)
const PilatesAlunosRoute = PilatesAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => PilatesRoute,
} as any)
const PilatesAlunoIdRoute = PilatesAlunoIdRouteImport.update({
  id: '/$alunoId',
  path: '/$alunoId',
  getParentRoute: () => PilatesAlunosRoute,
} as any)
const VisualizacaoRoute = VisualizacaoRouteImport.update({
  id: '/visualizacao',
  path: '/visualizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizacaoPilatesRoute = VisualizacaoPilatesRouteImport.update({
  id: '/pilates',
  path: '/pilates',
  getParentRoute: () => VisualizacaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRouteWithChildren
  '/pilates/alunos': typeof PilatesAlunosRouteWithChildren
  '/pilates/configuracoes': typeof PilatesConfiguracoesRoute
  '/pilates/aulas-experimentais': typeof PilatesAulasExperimentaisRoute
  '/pilates/alunos/$alunoId': typeof PilatesAlunoIdRoute
  '/visualizacao': typeof VisualizacaoRouteWithChildren
  '/visualizacao/pilates': typeof VisualizacaoPilatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRouteWithChildren
  '/pilates/alunos': typeof PilatesAlunosRoute
  '/pilates/configuracoes': typeof PilatesConfiguracoesRoute
  '/pilates/aulas-experimentais': typeof PilatesAulasExperimentaisRoute
  '/visualizacao': typeof VisualizacaoRouteWithChildren
  '/visualizacao/pilates': typeof VisualizacaoPilatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRouteWithChildren
  '/pilates/alunos': typeof PilatesAlunosRoute
  '/pilates/configuracoes': typeof PilatesConfiguracoesRoute
  '/visualizacao': typeof VisualizacaoRouteWithChildren
  '/visualizacao/pilates': typeof VisualizacaoPilatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/osteopatia'
    | '/pilates'
    | '/pilates/alunos'
    | '/pilates/configuracoes'
    | '/pilates/aulas-experimentais'
    | '/pilates/alunos/$alunoId'
    | '/visualizacao'
    | '/visualizacao/pilates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/osteopatia'
    | '/pilates'
    | '/pilates/alunos'
    | '/pilates/configuracoes'
    | '/visualizacao'
    | '/visualizacao/pilates'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/osteopatia'
    | '/pilates'
    | '/pilates/alunos'
    | '/pilates/configuracoes'
    | '/visualizacao'
    | '/visualizacao/pilates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OsteopatiaRoute: typeof OsteopatiaRoute
  PilatesRoute: typeof PilatesRouteWithChildren
  VisualizacaoRoute: typeof VisualizacaoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osteopatia': {
      id: '/osteopatia'
      path: '/osteopatia'
      fullPath: '/osteopatia'
      preLoaderRoute: typeof OsteopatiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilates': {
      id: '/pilates'
      path: '/pilates'
      fullPath: '/pilates'
      preLoaderRoute: typeof PilatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilates/alunos': {
      id: '/pilates/alunos'
      path: '/alunos'
      fullPath: '/pilates/alunos'
      preLoaderRoute: typeof PilatesAlunosRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/aulas-experimentais': { id: '/pilates/aulas-experimentais', path: '/aulas-experimentais', fullPath: '/pilates/aulas-experimentais', preLoaderRoute: typeof PilatesAulasExperimentaisRouteImport, parentRoute: typeof PilatesRoute }
    '/pilates/configuracoes': {
      id: '/pilates/configuracoes'
      path: '/configuracoes'
      fullPath: '/pilates/configuracoes'
      preLoaderRoute: typeof PilatesConfiguracoesRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/alunos/$alunoId': {
      id: '/pilates/alunos/$alunoId'
      path: '/$alunoId'
      fullPath: '/pilates/alunos/$alunoId'
      preLoaderRoute: typeof PilatesAlunoIdRouteImport
      parentRoute: typeof PilatesAlunosRoute
    }
    '/visualizacao': {
      id: '/visualizacao'
      path: '/visualizacao'
      fullPath: '/visualizacao'
      preLoaderRoute: typeof VisualizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizacao/pilates': {
      id: '/visualizacao/pilates'
      path: '/pilates'
      fullPath: '/visualizacao/pilates'
      preLoaderRoute: typeof VisualizacaoPilatesRouteImport
      parentRoute: typeof VisualizacaoRoute
    }
  }
}

interface PilatesAlunosRouteChildren {
  PilatesAlunoIdRoute: typeof PilatesAlunoIdRoute
}

const PilatesAlunosRouteChildren: PilatesAlunosRouteChildren = {
  PilatesAlunoIdRoute: PilatesAlunoIdRoute,
}

const PilatesAlunosRouteWithChildren = PilatesAlunosRoute._addFileChildren(
  PilatesAlunosRouteChildren,
)

interface PilatesRouteChildren {
  PilatesAlunosRoute: typeof PilatesAlunosRoute
  PilatesConfiguracoesRoute: typeof PilatesConfiguracoesRoute
  PilatesAulasExperimentaisRoute: typeof PilatesAulasExperimentaisRoute
}

const PilatesRouteChildren: PilatesRouteChildren = {
  PilatesAlunosRoute: PilatesAlunosRouteWithChildren,
  PilatesConfiguracoesRoute: PilatesConfiguracoesRoute,
  PilatesAulasExperimentaisRoute: PilatesAulasExperimentaisRoute,
}

const PilatesRouteWithChildren = PilatesRoute._addFileChildren(
  PilatesRouteChildren,
)

interface VisualizacaoRouteChildren {
  VisualizacaoPilatesRoute: typeof VisualizacaoPilatesRoute
}

const VisualizacaoRouteChildren: VisualizacaoRouteChildren = {
  VisualizacaoPilatesRoute: VisualizacaoPilatesRoute,
}

const VisualizacaoRouteWithChildren = VisualizacaoRoute._addFileChildren(
  VisualizacaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OsteopatiaRoute: OsteopatiaRoute,
  PilatesRoute: PilatesRouteWithChildren,
  VisualizacaoRoute: VisualizacaoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
