/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OsteopatiaRouteImport } from './routes/osteopatia'
import { Route as PilatesRouteImport } from './routes/pilates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OsteopatiaRoute = OsteopatiaRouteImport.update({
  id: '/osteopatia',
  path: '/osteopatia',
  getParentRoute: () => rootRouteImport,
} as any)
const PilatesRoute = PilatesRouteImport.update({
  id: '/pilates',
  path: '/pilates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/osteopatia' | '/pilates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/osteopatia' | '/pilates'
  id: '__root__' | '/' | '/login' | '/osteopatia' | '/pilates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OsteopatiaRoute: typeof OsteopatiaRoute
  PilatesRoute: typeof PilatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osteopatia': {
      id: '/osteopatia'
      path: '/osteopatia'
      fullPath: '/osteopatia'
      preLoaderRoute: typeof OsteopatiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilates': {
      id: '/pilates'
      path: '/pilates'
      fullPath: '/pilates'
      preLoaderRoute: typeof PilatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OsteopatiaRoute: OsteopatiaRoute,
  PilatesRoute: PilatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
