/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OsteopatiaRouteImport } from './routes/osteopatia'
import { Route as PilatesRouteImport } from './routes/pilates'
import { Route as VisualizacaoRouteImport } from './routes/visualizacao'
import { Route as PilatesAlertasRouteImport } from './routes/pilates.alertas'
import { Route as PilatesAlunosRouteImport } from './routes/pilates.alunos'
import { Route as PilatesAulasAvulsasRouteImport } from './routes/pilates.aulas-avulsas'
import { Route as PilatesAulasExperimentaisRouteImport } from './routes/pilates.aulas-experimentais'
import { Route as PilatesConfiguracoesRouteImport } from './routes/pilates.configuracoes'
import { Route as PilatesFechamentosRouteImport } from './routes/pilates.fechamentos'
import { Route as PilatesFluxoCaixaRouteImport } from './routes/pilates.fluxo-caixa'
import { Route as VisualizacaoPilatesRouteImport } from './routes/visualizacao.pilates'
import { Route as PilatesAlunosAlunoIdRouteImport } from './routes/pilates.alunos.$alunoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OsteopatiaRoute = OsteopatiaRouteImport.update({
  id: '/osteopatia',
  path: '/osteopatia',
  getParentRoute: () => rootRouteImport,
} as any)
const PilatesRoute = PilatesRouteImport.update({
  id: '/pilates',
  path: '/pilates',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizacaoRoute = VisualizacaoRouteImport.update({
  id: '/visualizacao',
  path: '/visualizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PilatesAlertasRoute = PilatesAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => PilatesRoute,
} as any)
const PilatesAlunosRoute = PilatesAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => PilatesRoute,
} as any)
const PilatesAulasAvulsasRoute = PilatesAulasAvulsasRouteImport.update({
  id: '/aulas-avulsas',
  path: '/aulas-avulsas',
  getParentRoute: () => PilatesRoute,
} as any)
const PilatesAulasExperimentaisRoute =
  PilatesAulasExperimentaisRouteImport.update({
    id: '/aulas-experimentais',
    path: '/aulas-experimentais',
    getParentRoute: () => PilatesRoute,
  } as any)
const PilatesConfiguracoesRoute = PilatesConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PilatesRoute,
} as any)
const PilatesFechamentosRoute = PilatesFechamentosRouteImport.update({
  id: '/fechamentos',
  path: '/fechamentos',
  getParentRoute: () => PilatesRoute,
} as any)
const PilatesFluxoCaixaRoute = PilatesFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => PilatesRoute,
} as any)
const VisualizacaoPilatesRoute = VisualizacaoPilatesRouteImport.update({
  id: '/pilates',
  path: '/pilates',
  getParentRoute: () => VisualizacaoRoute,
} as any)
const PilatesAlunosAlunoIdRoute = PilatesAlunosAlunoIdRouteImport.update({
  id: '/$alunoId',
  path: '/$alunoId',
  getParentRoute: () => PilatesAlunosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRouteWithChildren
  '/visualizacao': typeof VisualizacaoRouteWithChildren
  '/pilates/alertas': typeof PilatesAlertasRoute
  '/pilates/alunos': typeof PilatesAlunosRouteWithChildren
  '/pilates/aulas-avulsas': typeof PilatesAulasAvulsasRoute
  '/pilates/aulas-experimentais': typeof PilatesAulasExperimentaisRoute
  '/pilates/configuracoes': typeof PilatesConfiguracoesRoute
  '/pilates/fechamentos': typeof PilatesFechamentosRoute
  '/pilates/fluxo-caixa': typeof PilatesFluxoCaixaRoute
  '/visualizacao/pilates': typeof VisualizacaoPilatesRoute
  '/pilates/alunos/$alunoId': typeof PilatesAlunosAlunoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRouteWithChildren
  '/visualizacao': typeof VisualizacaoRouteWithChildren
  '/pilates/alertas': typeof PilatesAlertasRoute
  '/pilates/alunos': typeof PilatesAlunosRouteWithChildren
  '/pilates/aulas-avulsas': typeof PilatesAulasAvulsasRoute
  '/pilates/aulas-experimentais': typeof PilatesAulasExperimentaisRoute
  '/pilates/configuracoes': typeof PilatesConfiguracoesRoute
  '/pilates/fechamentos': typeof PilatesFechamentosRoute
  '/pilates/fluxo-caixa': typeof PilatesFluxoCaixaRoute
  '/visualizacao/pilates': typeof VisualizacaoPilatesRoute
  '/pilates/alunos/$alunoId': typeof PilatesAlunosAlunoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/osteopatia': typeof OsteopatiaRoute
  '/pilates': typeof PilatesRouteWithChildren
  '/visualizacao': typeof VisualizacaoRouteWithChildren
  '/pilates/alertas': typeof PilatesAlertasRoute
  '/pilates/alunos': typeof PilatesAlunosRouteWithChildren
  '/pilates/aulas-avulsas': typeof PilatesAulasAvulsasRoute
  '/pilates/aulas-experimentais': typeof PilatesAulasExperimentaisRoute
  '/pilates/configuracoes': typeof PilatesConfiguracoesRoute
  '/pilates/fechamentos': typeof PilatesFechamentosRoute
  '/pilates/fluxo-caixa': typeof PilatesFluxoCaixaRoute
  '/visualizacao/pilates': typeof VisualizacaoPilatesRoute
  '/pilates/alunos/$alunoId': typeof PilatesAlunosAlunoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/osteopatia'
    | '/pilates'
    | '/visualizacao'
    | '/pilates/alertas'
    | '/pilates/alunos'
    | '/pilates/aulas-avulsas'
    | '/pilates/aulas-experimentais'
    | '/pilates/configuracoes'
    | '/pilates/fechamentos'
    | '/pilates/fluxo-caixa'
    | '/visualizacao/pilates'
    | '/pilates/alunos/$alunoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/osteopatia'
    | '/pilates'
    | '/visualizacao'
    | '/pilates/alertas'
    | '/pilates/alunos'
    | '/pilates/aulas-avulsas'
    | '/pilates/aulas-experimentais'
    | '/pilates/configuracoes'
    | '/pilates/fechamentos'
    | '/pilates/fluxo-caixa'
    | '/visualizacao/pilates'
    | '/pilates/alunos/$alunoId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/osteopatia'
    | '/pilates'
    | '/visualizacao'
    | '/pilates/alertas'
    | '/pilates/alunos'
    | '/pilates/aulas-avulsas'
    | '/pilates/aulas-experimentais'
    | '/pilates/configuracoes'
    | '/pilates/fechamentos'
    | '/pilates/fluxo-caixa'
    | '/visualizacao/pilates'
    | '/pilates/alunos/$alunoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OsteopatiaRoute: typeof OsteopatiaRoute
  PilatesRoute: typeof PilatesRouteWithChildren
  VisualizacaoRoute: typeof VisualizacaoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osteopatia': {
      id: '/osteopatia'
      path: '/osteopatia'
      fullPath: '/osteopatia'
      preLoaderRoute: typeof OsteopatiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilates': {
      id: '/pilates'
      path: '/pilates'
      fullPath: '/pilates'
      preLoaderRoute: typeof PilatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizacao': {
      id: '/visualizacao'
      path: '/visualizacao'
      fullPath: '/visualizacao'
      preLoaderRoute: typeof VisualizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilates/alertas': {
      id: '/pilates/alertas'
      path: '/alertas'
      fullPath: '/pilates/alertas'
      preLoaderRoute: typeof PilatesAlertasRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/alunos': {
      id: '/pilates/alunos'
      path: '/alunos'
      fullPath: '/pilates/alunos'
      preLoaderRoute: typeof PilatesAlunosRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/aulas-avulsas': {
      id: '/pilates/aulas-avulsas'
      path: '/aulas-avulsas'
      fullPath: '/pilates/aulas-avulsas'
      preLoaderRoute: typeof PilatesAulasAvulsasRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/aulas-experimentais': {
      id: '/pilates/aulas-experimentais'
      path: '/aulas-experimentais'
      fullPath: '/pilates/aulas-experimentais'
      preLoaderRoute: typeof PilatesAulasExperimentaisRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/configuracoes': {
      id: '/pilates/configuracoes'
      path: '/configuracoes'
      fullPath: '/pilates/configuracoes'
      preLoaderRoute: typeof PilatesConfiguracoesRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/fechamentos': {
      id: '/pilates/fechamentos'
      path: '/fechamentos'
      fullPath: '/pilates/fechamentos'
      preLoaderRoute: typeof PilatesFechamentosRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/pilates/fluxo-caixa': {
      id: '/pilates/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/pilates/fluxo-caixa'
      preLoaderRoute: typeof PilatesFluxoCaixaRouteImport
      parentRoute: typeof PilatesRoute
    }
    '/visualizacao/pilates': {
      id: '/visualizacao/pilates'
      path: '/pilates'
      fullPath: '/visualizacao/pilates'
      preLoaderRoute: typeof VisualizacaoPilatesRouteImport
      parentRoute: typeof VisualizacaoRoute
    }
    '/pilates/alunos/$alunoId': {
      id: '/pilates/alunos/$alunoId'
      path: '/$alunoId'
      fullPath: '/pilates/alunos/$alunoId'
      preLoaderRoute: typeof PilatesAlunosAlunoIdRouteImport
      parentRoute: typeof PilatesAlunosRoute
    }
  }
}

interface PilatesAlunosRouteChildren {
  PilatesAlunosAlunoIdRoute: typeof PilatesAlunosAlunoIdRoute
}

const PilatesAlunosRouteChildren: PilatesAlunosRouteChildren = {
  PilatesAlunosAlunoIdRoute: PilatesAlunosAlunoIdRoute,
}

const PilatesAlunosRouteWithChildren = PilatesAlunosRoute._addFileChildren(
  PilatesAlunosRouteChildren,
)

interface PilatesRouteChildren {
  PilatesAlertasRoute: typeof PilatesAlertasRoute
  PilatesAlunosRoute: typeof PilatesAlunosRouteWithChildren
  PilatesAulasAvulsasRoute: typeof PilatesAulasAvulsasRoute
  PilatesAulasExperimentaisRoute: typeof PilatesAulasExperimentaisRoute
  PilatesConfiguracoesRoute: typeof PilatesConfiguracoesRoute
  PilatesFechamentosRoute: typeof PilatesFechamentosRoute
  PilatesFluxoCaixaRoute: typeof PilatesFluxoCaixaRoute
}

const PilatesRouteChildren: PilatesRouteChildren = {
  PilatesAlertasRoute: PilatesAlertasRoute,
  PilatesAlunosRoute: PilatesAlunosRouteWithChildren,
  PilatesAulasAvulsasRoute: PilatesAulasAvulsasRoute,
  PilatesAulasExperimentaisRoute: PilatesAulasExperimentaisRoute,
  PilatesConfiguracoesRoute: PilatesConfiguracoesRoute,
  PilatesFechamentosRoute: PilatesFechamentosRoute,
  PilatesFluxoCaixaRoute: PilatesFluxoCaixaRoute,
}

const PilatesRouteWithChildren =
  PilatesRoute._addFileChildren(PilatesRouteChildren)

interface VisualizacaoRouteChildren {
  VisualizacaoPilatesRoute: typeof VisualizacaoPilatesRoute
}

const VisualizacaoRouteChildren: VisualizacaoRouteChildren = {
  VisualizacaoPilatesRoute: VisualizacaoPilatesRoute,
}

const VisualizacaoRouteWithChildren = VisualizacaoRoute._addFileChildren(
  VisualizacaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OsteopatiaRoute: OsteopatiaRoute,
  PilatesRoute: PilatesRouteWithChildren,
  VisualizacaoRoute: VisualizacaoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
